### PR TITLE
expose public routetable id

### PR DESCRIPTION
**Pull request by houqp**
this PR adds back the public attribute added in #10

### CODE REVIEW

**Comment by houqp** [comment]
I have a quick question regarding exposing children resources as public attributes. What's the reason for choosing `publicRouteTable.id` instead of just `publicRouteTable`? Wouldn't the latter result in a more flexible API?

**Comment by CyrusNajmabadi** [comment]
> I have a quick question regarding exposing children resources as public attributes. What's the reason for choosing publicRouteTable.id instead of just publicRouteTable? Wouldn't the latter result in a more flexible API?

We don't have a hard/fast rule here.  You're definitely correct that this would make things more flexible.  However, it would also lock us into a fixed implementation.  Consider, for example, if we wanted to change things so that this information could be provided by configuration, and no actual resource was created.  Just exposing the id gives us that flexibility.

That said, i would not have a problem if you actually wanted to expose the route table directly.  So feel free to make that change if that would help you out :)

**Comment by CyrusNajmabadi** [comment]
I'll wait for your decision on if you want to change things.  If you're ok as-is, i'll happily merge.  Otherwise, if you'd prefer to just expose the table, then feel free to make the change, and then ping me once things pass.  thanks!

**Comment by houqp** [comment]
Thanks for the explanation, I will keep it as is for now since the original PR also exposes it as id string. For our own use-case, an id is good enough :)

**Comment by CyrusNajmabadi** [comment]
Thanks much!

**Pull request merged**
